sudo: required
services:
  - docker
language: python
python:
  - "2.7"
  - "3.5"

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: WTLY2cyHCUoGTxVukNXqCBvhTVK9Dk82CvXE0w6HUVNA5psrE+G3HACx5jWaglK7ZZ0Ajmjt3RqnKL3t1Y1qAQrp2zpnRhFGzHmJQRI7uVGZq9kZN6Jsql9uzOvPcQPlu9A9FGM/Tj7YanVx86v/j/Q/zOVVwuc9u2QCk6e3WSkBncb2/9YMtg8LAjQyfryQa03xWxGgMdrB/Q2gdpAE+5aih128zhLN5h0HXdWpO9OqC9UW/ryBEdFu/FslMFfklUK+TCFuQ3+BKNQ0y0+43UO4e5VvRsz+PL8Ip4Y23eYjo5qBB+79I/U77ybqXBPFFtAnKpx1hVO1KHxaguA2A1Cn3fo8r+1s5rojQ8Ml17/aNxsSufBZ3SgfVDUlm6JQVfFSyt2LxvfIwsite5+vfEU1drjGTtV4awd/8fFn503h0sGgnVAMesAQJbk5oEfl1zfJs1/7/7sKGnR0wBslgY0d7yo5KV/8DEG5atelenOyjH3ryS+2R3dZVs5j93o9asom9LVsbglzo6oIXWsw97/2IlKzk+hRc9dog7jB+OMeXp8ToH/y06veQeIG9S/OHqckaK0PMtWYsjngDg3UEf9x7AHxTh6YGvcbF0vT90SqZyPwE8Aja6ZVHh8iqm35QFcY2eWQHduB36LG747yuMNmMI2yHe3enxRiu8fJ0o8=
  - secure: bpaDZulE5LxE9ic0w/H1nV6Buv8OswDQw/I7KMhKqShX3h2Ys3BowzZnAs7ReJenPKaGiqdm86t8w9qewr9ISh/IK03QaOFL4WPznvZB4WhgXGIBRXgM8G5sJOdjBJAUy++GKLZquLHARNsMedvLA0uHKLwPCBgAFxzZubNCtFwnJ/x7sFUfuqEOCirZpZflyq2fOUXNopnS5bqzaMoErVFtgzwG3GGBNx7QgNQ1NAv3pnaQWCSbYuIdvoslUkK6NAPnUcIxP6HwaYDhEuadjlQGVjn5oFwVKHIJlfPPrW1gS21GnUTTAsDQo7rsTvn9rYL+dzBGIP4+g1eDSRaALH8xAfwM8aI7LGu2+4q02hBoa8DxTt4JwSwUB1phQuaGFDRtAvJ+0kiSTwqifcoIwPiszMhcwoGF3qmTvFWFqZSmIAZJvUSszEj5rAVZ88FVXFd3b0MGUGNZhjlh4aiojfHI+AWguQU50JieZY3lNvgSuwi+mahm+LXb3iG5wuo45BxF3A0+UBrg3tfp9aGQ1yp9L5auSgBdQfXz9LVqy+KMJaJybdQDe5eXJmV8oD8crm3tq30NlFNwZuW2nTDUgFr4FCo9dbyLhoE8FYZ04dS7N89selyGxQVEtEFO50fmD1KSQAQom5cvxihNcQhgZp+DY1MdG7hejjYkOKM/HvE=

after_success:
- echo "$DOCKER_USER"
- echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
- export REPO=stefanccaraiman/demo-proxy
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build --pull --force-rm -f Dockerfile -t $REPO:latest .
- docker push $REPO:latest


install: pip install tox
script:
  - echo "Running tests."
