sudo: required
services:
- docker
language: python
python:
  - 2.7
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: CiRur6qjCLCOD8ur2KjG3NB/rXXqz8x0yU5HFowqPHwp6esWu29aphGcE4gLg1UCQcL+fEC3oYWSMf1VWQh30Un0i2HeQ+6Sjc4GNRmOW2gPRfar6gMSdTwbZ0F9dPTrrAzOsM127NcooMBdm7e0cQ7i64YmZ3NhP3WMwrCYFy+sjoc7/1mP5ck8pOHPjE92e2MAz2oAzTeS2OPctYeJYlU6IY+TmkCR+Ca4TbjIk9rKScQZVX0lGCXs9xFLWJ31138BnaE/bVcVdIYcPhKUSNP5NTffse6nP5pDTkg4LMUYGMAreX1UFL2O1n+0R8Ra69DuWMlmPFe+86DrGDe7hU9YnUK1+0JIaF70PKXsMP2uWviCeRD38eOjkDBvBrX4FVpqiHIZQ3O/13WMpVK2vv29VGt6h3plAr6U/UdwqXBQisCD12/EWHHMnCVWGBUSNXfAVCgOwxPf4RZq5/1wwNPwUSvPM3VRfP/jKvMBDy361kv1+EfCHEr+TLjS5uVkp/15FiRghUe613xvCehKpcnwyFi4NzkN/l5vSBbRRmH0LV+FszmGwW8CrwEtf0KeY5kFWvFXsLKxvTzW3xuC3kWTmxx3PCIGWgKD2Oj4I/EUqytmkGgPAEusu7m9XJerHTyJeHBlYMEidbvsS1LppDmLgfEq26ZDe3g9Dn22hnE=
  - secure: WTLY2cyHCUoGTxVukNXqCBvhTVK9Dk82CvXE0w6HUVNA5psrE+G3HACx5jWaglK7ZZ0Ajmjt3RqnKL3t1Y1qAQrp2zpnRhFGzHmJQRI7uVGZq9kZN6Jsql9uzOvPcQPlu9A9FGM/Tj7YanVx86v/j/Q/zOVVwuc9u2QCk6e3WSkBncb2/9YMtg8LAjQyfryQa03xWxGgMdrB/Q2gdpAE+5aih128zhLN5h0HXdWpO9OqC9UW/ryBEdFu/FslMFfklUK+TCFuQ3+BKNQ0y0+43UO4e5VvRsz+PL8Ip4Y23eYjo5qBB+79I/U77ybqXBPFFtAnKpx1hVO1KHxaguA2A1Cn3fo8r+1s5rojQ8Ml17/aNxsSufBZ3SgfVDUlm6JQVfFSyt2LxvfIwsite5+vfEU1drjGTtV4awd/8fFn503h0sGgnVAMesAQJbk5oEfl1zfJs1/7/7sKGnR0wBslgY0d7yo5KV/8DEG5atelenOyjH3ryS+2R3dZVs5j93o9asom9LVsbglzo6oIXWsw97/2IlKzk+hRc9dog7jB+OMeXp8ToH/y06veQeIG9S/OHqckaK0PMtWYsjngDg3UEf9x7AHxTh6YGvcbF0vT90SqZyPwE8Aja6ZVHh8iqm35QFcY2eWQHduB36LG747yuMNmMI2yHe3enxRiu8fJ0o8=
  - secure: bpaDZulE5LxE9ic0w/H1nV6Buv8OswDQw/I7KMhKqShX3h2Ys3BowzZnAs7ReJenPKaGiqdm86t8w9qewr9ISh/IK03QaOFL4WPznvZB4WhgXGIBRXgM8G5sJOdjBJAUy++GKLZquLHARNsMedvLA0uHKLwPCBgAFxzZubNCtFwnJ/x7sFUfuqEOCirZpZflyq2fOUXNopnS5bqzaMoErVFtgzwG3GGBNx7QgNQ1NAv3pnaQWCSbYuIdvoslUkK6NAPnUcIxP6HwaYDhEuadjlQGVjn5oFwVKHIJlfPPrW1gS21GnUTTAsDQo7rsTvn9rYL+dzBGIP4+g1eDSRaALH8xAfwM8aI7LGu2+4q02hBoa8DxTt4JwSwUB1phQuaGFDRtAvJ+0kiSTwqifcoIwPiszMhcwoGF3qmTvFWFqZSmIAZJvUSszEj5rAVZ88FVXFd3b0MGUGNZhjlh4aiojfHI+AWguQU50JieZY3lNvgSuwi+mahm+LXb3iG5wuo45BxF3A0+UBrg3tfp9aGQ1yp9L5auSgBdQfXz9LVqy+KMJaJybdQDe5eXJmV8oD8crm3tq30NlFNwZuW2nTDUgFr4FCo9dbyLhoE8FYZ04dS7N89selyGxQVEtEFO50fmD1KSQAQom5cvxihNcQhgZp+DY1MdG7hejjYkOKM/HvE=
after_success:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- export REPO=stefanccaraiman/flask-app
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
script:
  - echo "Running tests."